SOCIAL_AUTH_TWITTER_KEY = 'bZtbauJOdIiEnAFVXyNOw0tEY'
SOCIAL_AUTH_TWITTER_SECRET = 'TSJdveBUuYrWKPrKMx4bkGGOvxj7AqZt7ltITCfonD4Fa2vuat'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'